"""user email verified bool

Revision ID: 12173c6f037a
Revises: 2025030502
Create Date: 2025-03-12 19:40:46.486495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12173c6f037a'
down_revision = '2025030502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###